// FernetCpp compatibility test
// Build: g++ -std=c++17 -I. test_fernet.cpp -o test_fernet -lcryptopp

#include "fernet.h"
#include <cassert>
#include <cstring>
#include <iostream>
#include <string>

static int tests = 0, passed = 0;

#define TEST(name)                              \
    do {                                        \
        tests++;                                \
        std::cout << "  " << (name) << " ... "; \
    } while (0)
#define OK                              \
    do {                                \
        passed++;                       \
        std::cout << "OK" << std::endl; \
    } while (0)
#define FAIL(msg)                                   \
    do {                                            \
        std::cout << "FAIL" << std::endl;           \
        std::cerr << "       " << msg << std::endl; \
    } while (0)

int main() {
    std::cout << "FernetCpp Tests" << std::endl << "===============" << std::endl;

    // -- C++ round-trip -------------------------------------------------

    std::cout << "C++ round-trip:" << std::endl;

    TEST("encrypt64/decrypt64");
    {
        FERNET fernet("", 300);
        std::string msg = "Hello, Fernet!";

        BYTE* token = nullptr;
        size_t tokenLen = 0;
        assert(fernet.encrypt64((BYTE*) msg.data(), msg.size(), &token, &tokenLen));

        BYTE* plain = nullptr;
        size_t plainLen = 0;
        bool ok = fernet.decrypt64(token, tokenLen, &plain, &plainLen);

        if (ok && plainLen == msg.size() && memcmp(plain, msg.data(), plainLen) == 0) {
            OK;
        } else {
            FAIL("round-trip mismatch");
        }
        free(token);
        if (ok)
            free(plain);
    }

    TEST("encrypt/decrypt (binary, error codes)");
    {
        FERNET fernet("", 300);
        std::string msg = "binary test";

        BYTE* token = nullptr;
        size_t tokenLen = 0;
        int rc = fernet.encrypt((BYTE*) msg.data(), msg.size(), &token, &tokenLen);
        if (rc != FERNET_OK) {
            FAIL("encrypt returned " << rc);
            free(token);
        } else {
            BYTE* plain = nullptr;
            size_t plainLen = 0;
            rc = fernet.decrypt(token, tokenLen, &plain, &plainLen);
            if (rc == FERNET_OK && plainLen == msg.size()
                && memcmp(plain, msg.data(), plainLen) == 0) {
                OK;
            } else {
                FAIL("decrypt returned " << rc);
            }
            free(token);
            if (rc == FERNET_OK)
                free(plain);
        }
    }

    TEST("decrypt with wrong key fails");
    {
        FERNET fernet1("", 300);
        FERNET fernet2("", 300);
        std::string msg = "secret";

        BYTE* token = nullptr;
        size_t tokenLen = 0;
        fernet1.encrypt64((BYTE*) msg.data(), msg.size(), &token, &tokenLen);

        BYTE* plain = nullptr;
        size_t plainLen = 0;
        bool ok = fernet2.decrypt64(token, tokenLen, &plain, &plainLen);
        if (!ok) {
            OK;
        } else {
            FAIL("should have failed with wrong key");
            free(plain);
        }
        free(token);
    }

    TEST("decrypt expired token fails");
    {
        FERNET fernet("", 0);  // 0-second TTL
        std::string msg = "expired";

        BYTE* token = nullptr;
        size_t tokenLen = 0;
        fernet.encrypt64((BYTE*) msg.data(), msg.size(), &token, &tokenLen);

        BYTE* plain = nullptr;
        size_t plainLen = 0;
        bool ok = fernet.decrypt64(token, tokenLen, &plain, &plainLen);
        if (!ok) {
            OK;
        } else {
            FAIL("should have failed (expired)");
            free(plain);
        }
        free(token);
    }

    TEST("get_key returns valid base64");
    {
        FERNET fernet;
        std::string key = fernet.get_key();
        if (key.size() == 44) {
            OK;
        } else {
            FAIL("key length " << key.size() << " (expected 44)");
        }
    }

    TEST("get_key_from_password");
    {
        std::string pw = "my-password";
        std::string key = get_key_from_password(pw);
        if (key.size() == 44) {
            OK;
        } else {
            FAIL("key length " << key.size() << " (expected 44)");
        }
    }

    // -- Python Fernet compatibility -------------------------------------
    // Token generated by: python3 -c "
    //   from cryptography.fernet import Fernet
    //   key = Fernet.generate_key()
    //   f = Fernet(key)
    //   print(key.decode(), f.encrypt(b'Hello, Fernet!').decode())
    // "

    std::cout << "Python Fernet compatibility:" << std::endl;

    const std::string pyKey = "azP7xePMjNqFOvXR4bCqQPYkGEpAWyBMrCZlX4vo1U4=";
    const std::string pyMsg = "Hello, Fernet!";

    // This token has == padding stripped (standard Python Fernet behavior).
    // If the token's natural base64 encoding has no padding, padded==stripped.
    const std::string pyToken =
        "gAAAAABqSlk0jtzNLmRj5vt5L5KOARgRb7EHDspBqwzpbpZ60N8VEBUx_JB486FkDZaDq7d9"
        "uRFwgcg2lPlpYmzKIAMFMnW_VQ==";
    // Stripped variant (Python's Fernet strips trailing =)
    const std::string pyTokenStripped =
        "gAAAAABqSlk0jtzNLmRj5vt5L5KOARgRb7EHDspBqwzpbpZ60N8VEBUx_JB486FkDZaDq7d9"
        "uRFwgcg2lPlpYmzKIAMFMnW_VQ";

    TEST("decrypt Python-encrypted token (padded)");
    {
        // Use TTL=3600 so token doesn't expire during test
        FERNET fernet(pyKey, 3600);
        BYTE* plain = nullptr;
        size_t plainLen = 0;
        bool ok = fernet.decrypt64((BYTE*) pyToken.data(), pyToken.size(), &plain, &plainLen);
        if (ok && plainLen == pyMsg.size() && memcmp(plain, pyMsg.data(), plainLen) == 0) {
            OK;
        } else {
            FAIL("failed to decrypt Python token (padded)");
        }
        if (ok)
            free(plain);
    }

    TEST("decrypt Python-encrypted token (unpadded)");
    {
        FERNET fernet(pyKey, 3600);
        BYTE* plain = nullptr;
        size_t plainLen = 0;
        bool ok = fernet.decrypt64(
            (BYTE*) pyTokenStripped.data(), pyTokenStripped.size(), &plain, &plainLen);
        if (ok && plainLen == pyMsg.size() && memcmp(plain, pyMsg.data(), plainLen) == 0) {
            OK;
        } else {
            FAIL("failed to decrypt Python token (unpadded)");
        }
        if (ok)
            free(plain);
    }

    TEST("C++ encrypt/decrypt with Python-generated key");
    {
        FERNET fernet(pyKey, 3600);
        BYTE* token = nullptr;
        size_t tokenLen = 0;
        fernet.encrypt64((BYTE*) pyMsg.data(), pyMsg.size(), &token, &tokenLen);

        BYTE* plain = nullptr;
        size_t plainLen = 0;
        bool ok = fernet.decrypt64(token, tokenLen, &plain, &plainLen);

        if (ok && plainLen == pyMsg.size() && memcmp(plain, pyMsg.data(), plainLen) == 0) {
            OK;
        } else {
            FAIL("round-trip with Python key failed");
        }
        free(token);
        if (ok)
            free(plain);
    }

    // -- Summary ---------------------------------------------------------

    std::cout << "---------------" << std::endl;
    std::cout << passed << "/" << tests << " tests passed." << std::endl;
    return (passed == tests) ? 0 : 1;
}
